# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f49820874db2fcfa073563ff575467c2e2592667c7ac4e17363a5360d7812e53ceb552de3b475fbb40432e1f76fdaa47e750e0d7272ab926d63dd4703207481a

test:
  secret_key_base: edeffc614d1222e7875fa6488bd1b7c44048dd2c37f72919878fd9d54210ecc7cc739a28c2599cfd3ad869b552bc197330471b25cd7ded119e8840afcf367b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
